const AllSCRIPTData = [
  {
    SCRIPTID: 1,
    TITLE: "Sales Newsletter",
    STATUS: "SAVED",
    SCRIPTTYPE: "SUMMARY",
    date: "10:20 AM, May 12, 2019",
  },
  {
    SCRIPTID: 2,
    TITLE: "Welcome SCRIPT",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 AM, April 28, 2019",
  },
  {
    SCRIPTID: 3,
    TITLE: "New Hire Introduction",
    STATUS: "DRAFT",
    SCRIPTTYPE: "SCRIPT",
    date: "4:15 PM, May 14, 2019",
  },
  {
    SCRIPTID: 4,
    TITLE: "Next Steps for Anthony",
    STATUS: "SAVED",
    SCRIPTTYPE: "TEMPLATE",
    date: "5:30 PM, May 20, 2019",
  },
  {
    SCRIPTID: 5,
    TITLE: "How can I change my email?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "SUMMARY",
    date: "11:00 AM, April 29, 2019",
  },
  {
    SCRIPTID: 6,
    TITLE: "How do I change admin permissions?",
    STATUS: "DRAFT",
    SCRIPTTYPE: "SCRIPT",
    date: "8:20 AM, May 1, 2019",
  },
  {
    SCRIPTID: 7,
    TITLE: "Do you offer support to free plans?",
    STATUS: "SAVED",
    SCRIPTTYPE: "SCRIPT",
    date: "6:30 PM, May 24, 2019",
  },
  {
    SCRIPTID: 8,
    TITLE: "How long is the free trial?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "SCRIPT",
    date: "2:30 PM, May 19, 2019",
  },
  {
    SCRIPTID: 9,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 10,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 11,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 12,
    TITLE: "Dummy data?",
    STATUS: "SAVED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 13,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 14,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 15,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 16,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 17,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2019",
  },
  {
    SCRIPTID: 18,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2020",
  },
  {
    SCRIPTID: 19,
    TITLE: "Dummy data?",
    STATUS: "RECORDED",
    SCRIPTTYPE: "TEMPLATE",
    date: "9:45 PM, May 20, 2020",
  },
];

module.exports = AllSCRIPTData;
